# Chezmoi Profile
#
# Inherits from navigator profile (pause-for-review workflow) and adds
# chezmoi-specific standards, roles, and agent templates.
#
# Excludes backend/frontend standards since chezmoi is for dotfiles, not web apps.

inherits_from: navigator

exclude_inherited_files:
  - standards/backend/*
  - standards/frontend/*
  - standards/global/commenting.md
  - standards/global/error-handling.md
